import globals from "globals";

export default [{
    files: ["src/**/*.js"],
    rules: {

        // https://eslint.org/docs/latest/rules/#possible-problems
        "array-callback-return": "error", 
        "constructor-super": "error", 
        "for-direction": "error", 
        "getter-return": "error", 
        "no-async-promise-executor": "error", 
        "no-await-in-loop": "error", 
        "no-class-assign": "error", 
        "no-compare-neg-zero": "error", 
        "no-cond-assign": "error", 
        "no-const-assign": "error", 
        "no-constant-binary-expression": "error", 
        "no-constant-condition": "error", 
        "no-control-regex": "error", 
        "no-debugger": "error", 
        "no-dupe-args": "error", 
        "no-dupe-class-members": "error", 
        "no-dupe-else-if": "error", 
        "no-dupe-keys": "error", 
        "no-duplicate-case": "error", 
        "no-duplicate-imports": "error", 
        "no-empty-character-class": "error", 
        "no-empty-pattern": "error", 
        "no-ex-assign": "error", 
        "no-fallthrough": "error", 
        "no-func-assign": "error", 
        "no-import-assign": "error", 
        "no-inner-declarations": "error", 
        "no-invalid-regexp": "error", 
        "no-irregular-whitespace": "error", 
        "no-loss-of-precision": "error", 
        "no-misleading-character-class": "error", 
        "no-new-native-nonconstructor": "error", 
        "no-obj-calls": "error", 
        "no-promise-executor-return": "error", 
        "no-prototype-builtins": "error", 
        "no-self-assign": "error", 
        "no-self-compare": "error", 
        "no-setter-return": "error", 
        "no-sparse-arrays": "error", 
        "no-template-curly-in-string": "error", 
        "no-this-before-super": "error", 
        "no-undef": "error",
        "no-unexpected-multiline": "error", 
        "no-unreachable": "error", 
        "no-unsafe-finally": "error", 
        "no-unsafe-negation": "error", 
        "no-unsafe-optional-chaining": "error", 
        "no-unused-private-class-members": "error",  
        "no-unused-vars": "error", 
        "no-use-before-define": "error", 
        "no-useless-backreference": "error", 
        "require-atomic-updates": "error", 
        "use-isnan": "error", 
        "valid-typeof": "error", 

        // https://eslint.org/docs/latest/rules/#suggestions
        "arrow-body-style": ["error", "always"], 
        camelcase: "error", 
        complexity: ["error", 15], 
        curly: "error", 
        "default-case": "error", 
        "default-case-last": "error", 
        "dot-notation": ["error", { allowKeywords: false }], 
        "eqeqeq": ["error", "always"], 
        "func-names": ["error", "as-needed"], 
        "func-style": ["error", "expression", { allowArrowFunctions: true }], 
        "id-length": ["error", { min: 2, exceptions: ["x", "y", "z"] }], 
        "logical-assignment-operators": ["error", "never"], 
        "new-cap": ["error", { newIsCap: true }], 
        "no-bitwise": ["error", { int32Hint: true }], 
        "no-caller": "error", 
        "no-case-declarations": "error", 
        "no-console": ["error", { allow: ["warn", "error"] }], 
        "no-continue": "error", 
        "no-delete-var": "error", 
        "no-else-return": "error", 
        "no-empty": "error", 
        "no-empty-static-block": "error", 
        "no-eval": "error", 
        "no-extend-native": "error", 
        "no-extra-bind": "error", 
        "no-extra-label": "error", 
        "no-global-assign": "error", 
        "no-implicit-coercion": "error", 
        "no-implied-eval": "error", 
        "no-invalid-this": "error", 
        "no-iterator": "error", 
        "no-label-var": "error", 
        "no-lone-blocks": "error", 
        "no-lonely-if": "error", 
        "no-loop-func": "error", 
        "no-multi-assign": "error", 
        "no-multi-str": "error", 
        "no-nested-ternary": "error", 
        "no-new-func": "error", 
        "no-new-wrappers": "error", 
        "no-nonoctal-decimal-escape": "error", 
        "no-octal": "error", 
        "no-proto": "error", 
        "no-redeclare": "error", 
        "no-regex-spaces": "error", 
        "no-return-assign": "error", 
        "no-shadow": "error", 
        "no-shadow-restricted-names": "error", 
        "no-throw-literal": "error", 
        "no-unneeded-ternary": "error", 
        "no-unused-labels": "error", 
        "no-useless-computed-key": "error", 
        "no-useless-concat": "error", 
        "no-useless-constructor": "error", 
        "no-useless-escape": "error", 
        "no-useless-rename": "error", 
        "no-var": "error", 
        "no-void": "error", 
        "no-with": "error", 
        "object-shorthand": "error", 
        "prefer-arrow-callback": ["error", { allowNamedFunctions: true }], 
        "one-var": ["error", "never"], 
        "prefer-const": "error", 
        "prefer-destructuring": "error", 
        "prefer-exponentiation-operator": "error", 
        "prefer-object-has-own": "error", 
        "prefer-object-spread": "error", 
        "prefer-promise-reject-errors": "error", 
        "prefer-rest-params": "error", 
        "prefer-spread": "error", 
        "require-yield": "error", 
        "sort-imports": ["error", {
            ignoreCase: true, 
            ignoreDeclarationSort: false, 
            ignoreMemberSort: false, 
            memberSyntaxSortOrder: ["none", "all", "multiple", "single"], 
            allowSeparatedGroups: false
        }], 
        strict: ["error", "never"], 
        "symbol-description": "error", 

    },
    languageOptions: { 
        globals: {
        ...globals.browser, 
        ...globals.node
        }
    },
}];
